### ISSUE TITLE
Time에서의 정확한 내부 동작 구조

### ISSUE THREAD

**Issue by mslee89** [carpedm20/korail2#29]
안녕하세요.
먼저, 이 라이브러리를 만들어주셔서 너무 고맙습니다.
너무 잘 쓰고 있어요.

다름이 아니라, search_train 에서 time 을 140000 으로 입력하면 어떤 시간대의 기차들이 잡히는지 알고 싶어서요.

주말 혹은 명절날에는 거의 안잡히고.. 여유 좌석이 있으면 금방 잡히더라구요.

만약 time 부분에 140000 을 입력하게 되면 14:00:00시부터 1초마다 1값이 증가하면서 예약 가능한 열차를 확인하나요 ??

코드를 봐도 전혀 이해가 안되네요 ㅠ

**Comment by sng2c** [comment]
코레일톡앱에서 어떻게 작동하는지 한번 보세요. ^^
