### ISSUE TITLE
로그인 실패 에러

### ISSUE THREAD

**Issue by lekangqaz** [carpedm20/korail2#47]
현재 로그인 단계에서 자꾸 False 가 나고 있습니다. 아이디 2개로 검증해도 똑같습니다. 다른 분은 잘 작동하나요? 아니라면 어떤 문제일까요?

**Comment by GeunSam2** [comment]
api 스펙이 바뀐 것 같아요.
response를 까보니 이런 응답이 나오네요.
`{'h_msg_cd': 'SUPDATE', 'strResult': 'SUCC', 'h_msg_txt': '최신버전으로 업데이트하신 후 이용하여 주십시오.'}`

요청보낼 때 파라미터로 전달했던 Version 정보가 키워드인 것 같은데, 간단한 리버싱으로 해당 버전정보만 바꿔서 전달해봤는데 여전히 안되네요..
버전이 바뀌면서 api스펙 자체가 바뀐것 같은데 어느정도 규모로 변경이 일어난건지 가늠이 안되어서 일단 여기로 찾아왔어요.

**Comment by GeunSam2** [comment]
주말에 좀더 시간내서 패킷을 까봐야겠네요..

**Comment by dhfhfk** [comment]
#48 문제를 해결해 PR을 생성했습니다. 제 환경에서는 문제 없이 작동하는데 다른 분들은 정상적으로 작동하는지 테스트 해주시면 감사하겠습니다.
